AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Storage Security
Resources:
  filterBucketObjactsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-filterBucketObjactsLambda
      CodeUri: s3://aws-serverless-storage-security-filter-bucket-objects/filter_bucket_objects_1.0.0.zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      MemorySize: 3008
      Timeout: 120
      Tracing: Active
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub "${fsspromote}"
        - S3CrudPolicy:
            BucketName: !Sub "${fssquarantine}"
      Environment:
        Variables:
          PROMOTEBUCKET: !Ref fsspromote
          QUARANTINEBUCKET: !Ref fssquarantine
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1

  fsspromote:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: fsspromote

  fssquarantine:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: fssquarantine

  SNSTopic1:
    Type: 'AWS::SNS::Topic'

  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: test@example.com
      Protocol: email
      TopicArn: !Ref SNSTopic1



